//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOOK_STORE.Data_Set
{
    using System;
    using System.Collections.Generic;
    
    public partial class Add_Stock_Table
    {
        public string Tracking_ID { get; set; }
        public string Existing_Stock { get; set; }
        public string New_Stock { get; set; }
        public string Total_Stock { get; set; }
        public string Cost { get; set; }
        public string Selling_Price { get; set; }
    }
}
