//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOOK_STORE.Data_Set
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finish_Order_Table
    {
        public string ID { get; set; }
        public string Net_Amount { get; set; }
        public string Discount { get; set; }
        public string Total_Amount { get; set; }
        public string Paid_Amount { get; set; }
        public string Balance_Amount { get; set; }
    }
}
