//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOOK_STORE.Data_Set
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Jumail_ProjectEntities : DbContext
    {
        public Jumail_ProjectEntities()
            : base("name=Jumail_ProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Add_Expence_Table> Add_Expence_Table { get; set; }
        public virtual DbSet<Add_NewBook_Table> Add_NewBook_Table { get; set; }
        public virtual DbSet<Add_Stock_Table> Add_Stock_Table { get; set; }
        public virtual DbSet<Finish_Order_Table> Finish_Order_Table { get; set; }
        public virtual DbSet<Login_Table> Login_Table { get; set; }
        public virtual DbSet<UC_ManageExpence_Table> UC_ManageExpence_Table { get; set; }
        public virtual DbSet<UC_ManageUser_Table> UC_ManageUser_Table { get; set; }
        public virtual DbSet<UC_Sales_Table> UC_Sales_Table { get; set; }
    }
}
