//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOOK_STORE.Data_Set
{
    using System;
    using System.Collections.Generic;
    
    public partial class UC_ManageUser_Table
    {
        public string User_Id { get; set; }
        public string Full_Name { get; set; }
        public string Phone { get; set; }
        public string NIC { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string User_Name { get; set; }
        public string Role { get; set; }
    }
}
